#!/usr/bin/env php
<?php
error_reporting(-1);

require __DIR__ . '/../vendor/autoload.php';

use Icecave\Chastity\Driver\Redis\RedisDriver;
use Icecave\Chastity\LockFactory;
use Icecave\Druid\UuidVersion4Generator;
use Predis\Client;

$factory = new LockFactory(
    new RedisDriver(
        new Client(),
        new UuidVersion4Generator()
    )
);

echo 'Waiting for lock ...' . PHP_EOL;

// Acquire a lock.
// The lock is automatically released when it goes out of scope.
$lock = $factory->acquire(
    'my-resource', // An arbitrary "resource" to lock
    2,             // The TTL of the lock, in seconds.
    300            // How long to wait for lock to be freed and acquired by this process (ie, timeout), in seconds.
);

echo 'Acquired!' . PHP_EOL;

for ($i = 0; $i < 3; ++$i) {
    sleep(1);
    echo 'Extending the lock for 1 second.' . PHP_EOL;
    $lock->extend(1);
}

echo 'Done!' . PHP_EOL;
